### PR TITLE
[v0.3-DeNas]common trainer

### PR DESCRIPTION
**Pull request by csdingbin**
Completed the common trainer refactor. The test works well for CNN trainer. Please help to review and merge. @xuechendi

### CODE REVIEW

**Review by xuechendi — APPROVED** [review]
LGTM

**Comment by xuechendi** [comment]
@csdingbin , I have went through this PR, approved.
But there are two small conflict, I tried to resolve today, but in that way, I will need to push to your Repo, so please help to resolve then I'll merge this PR.

**Comment by csdingbin** [comment]
> @csdingbin , I have went through this PR, approved. But there are two small conflict, I tried to resolve today, but in that way, I will need to push to your Repo, so please help to resolve then I'll merge this PR.

Got it.

**Comment by csdingbin** [comment]
> @csdingbin , I have went through this PR, approved. But there are two small conflict, I tried to resolve today, but in that way, I will need to push to your Repo, so please help to resolve then I'll merge this PR.

The conflicts resolved.

**Pull request merged**
