### PR TITLE
[v1.0 DENAS] return correct best structure for sigopt search

### PR DESCRIPTION
**Pull request by Peach-He**
sigopt search for VIT and ASR returns latest cdds and best structure, this PR is to fix this bug to return correct best structure.

### CODE REVIEW

**Comment by zigzagcai** [comment]
It might be a repo sync issue about DeNas original code. It was fixed several month ago about the public repo code was the unfixed one.
I have checked with MOSigoptSearchEngine.py and it is the one that return correct strcuture.
I have checked with previous DeNas run logs about ViT, and it the one that return correct structure.
ViT best structure in previous run,
(12, 3.0, 3.5, 4.0, 3.0, 3.0, 3.0, 4.0, 3.0, 4.0, 3.0, 4.0, 3.5, 9, 3, 3, 7, 3, 5, 3, 5, 6, 4, 3, 4, 320)
Corresponding SigOpt link: https://app.sigopt.com/experiment/532868

**Comment by zigzagcai** [comment]
The PR looks good with me.

**Comment by zigzagcai** [comment]
Having checked with Tao, it was typo bug when adding MOSigoptSearchEngine in https://github.com/intel-innersource/frameworks.bigdata.AIDK/commit/e92a9793db540e9c6e1fe0dc467dfea922f86a14#diff-89b0bb4c7fbd0f96e37453c52d43f2f4548dea71d657c2039e7d3a54a866607a

**Review by xuechendi — APPROVED** [review]
LGTM

**Pull request merged**
