### PR TITLE
[v1.2][ISSUE-306]Add Name and Password redaction Implementation with bigcode/startpii model

### PR DESCRIPTION
**Pull request by chaojun-zhang**
### What changes were proposed in this pull request?

Add Name and Password redaction with bigcode/startpii model

### Why are the changes needed?

EasyData Integration

### How was this patch tested?

UT

### CODE REVIEW

**Comment by chaojun-zhang** [comment]
This PR is based on #343 , please review and merge #343 first

**Comment by chaojun-zhang** [comment]
This PR is based on #343 , please merge #343 firstly

**Comment by xuechendi** [comment]
@chaojun-zhang , similar comments as sentense_split PR

**Comment by xuechendi** [comment]
@chaojun-zhang, please fix the UT
you forgot to add __init__.py to your new added folder, so sdist didn't include 'detect' folder to release, fix as below

image

Please do test with `python setup.py sdist && pip install dist/*` before submit your PR. It is second time you didn't add modules to __init__.py, please fix it, thanks

**Pull request closed without merging**
