### PR TITLE
[v1.1][ISSUE-227] Colab notebook demos for ResNet and MiniGo

### PR DESCRIPTION
**Pull request by zigzagcai**
### What changes were proposed in this pull request?
Add Colab Demo for ResNet and MiniGo

### Why are the changes needed?
Colab demo link needed

### How was this patch tested?
UT

### CODE REVIEW

**Comment by xuechendi** [comment]
@zigzagcai 
here is our defined format, you can also refer to 
https://github.com/intel/e2eAIOK/blob/main/demo/builtin/wnd/WND_DEMO.ipynb
https://github.com/intel/e2eAIOK/blob/main/demo/denas/asr/DENAS_ASR_DEMO.ipynb
image

**Comment by zigzagcai** [comment]
Got it. I will completed refine the format this morning. @xuechendi

**Comment by zigzagcai** [comment]
Completed demo refine for MiniGo and ResNet.

- [ ] Followed defined format, with reference to WnD format

**Comment by zigzagcai** [comment]
Completed demo refine and ready for merge.

**Comment by xuechendi** [comment]
@zigzagcai , I saw you only installed e2eaiok-sda and tf2.10, is that everything needed by Resnet demo to run?
Other files are looking good to me
image

**Pull request merged**
