### PR TITLE
Refine DLRM

### PR DESCRIPTION
**Pull request by csdingbin**

### CODE REVIEW

**Comment by Jian-Zhang** [comment]
Will you add instructions for all_in_one scripts?

**Comment by csdingbin** [comment]
> Will you add instructions for all_in_one scripts?

Yes, we will add it after the RecDP data processing + train connected.

**Comment by csdingbin** [comment]
> > Will you add instructions for all_in_one scripts?
> 
> Yes, we will add it after the RecDP data processing + train connected.
The train + inference all_in_one script added.

**Comment by Jian-Zhang** [comment]
Test failed. please check. @csdingbin  @zigzagcai

**Comment by csdingbin** [comment]
> Test failed. please check. @csdingbin @zigzagcai

Jenkins test met network issue. Submit another commit to trigger.
image

**Comment by csdingbin** [comment]
@Jian-Zhang @xuechendi  This PR CI/CD tests passed.

**Pull request merged**
