### PR TITLE
[V0.3 DENAS] Refactor the bert trainer in e2eaiok

### PR DESCRIPTION
**Pull request by tianyil1**
This PR is updated with the followings:

- Refactor the DENAS Bert features for using the common lib.
- Refine the common lib for supporting more features (etc., evaluation inner the training epoch).

It has been tested well in the local env:
image

### CODE REVIEW

**Comment by tianyil1** [comment]
> @tianyil1 @Peach-He @csdingbin @XinyaoWa , I realized one issue, I think dataloader in common lib should be used to define APIs and providing most common functions, but I realized actually you are also put actual dataloader there, https://github.com/intel/e2eAIOK/blob/main/e2eAIOK/common/trainer/data_builder.py#L19, https://github.com/intel/e2eAIOK/blob/e8dcbf633d7b4b1952d08ffc03425fdf898aaedc/e2eAIOK/common/trainer/data/nlp_build_datasets.py
> 
> I would like to confirm that adding cifar10, SQuAD and other dataset is a common work or can we put https://github.com/intel/e2eAIOK/blob/main/e2eAIOK/common/trainer/data_builder.py#L19-L47 to a seperate file and leaving the most basic function here?

Thanks for your suggestions. I will refactor this code.

**Comment by XinyaoWa** [comment]
> > @tianyil1 @Peach-He @csdingbin @XinyaoWa , I realized one issue, I think dataloader in common lib should be used to define APIs and providing most common functions, but I realized actually you are also put actual dataloader there, https://github.com/intel/e2eAIOK/blob/main/e2eAIOK/common/trainer/data_builder.py#L19, https://github.com/intel/e2eAIOK/blob/e8dcbf633d7b4b1952d08ffc03425fdf898aaedc/e2eAIOK/common/trainer/data/nlp_build_datasets.py
> > I would like to confirm that adding cifar10, SQuAD and other dataset is a common work or can we put https://github.com/intel/e2eAIOK/blob/main/e2eAIOK/common/trainer/data_builder.py#L19-L47 to a seperate file and leaving the most basic function here?
> 
> Thanks for your suggestions. I will refactor this code.

You can refer to the code on Model Adapter.
We only keep the most common operations(get dataset and dataloader) in common file: https://github.com/intel-innersource/frameworks.bigdata.AIDK/blob/transfer_learning/AIDK/TransferLearningKit/src/dataset/__init__.py
For each dataset, we will write a individual loader for it, such as: https://github.com/intel-innersource/frameworks.bigdata.AIDK/blob/transfer_learning/AIDK/TransferLearningKit/src/dataset/cifar100.py

**Comment by tianyil1** [comment]
> > > @tianyil1 @Peach-He @csdingbin @XinyaoWa , I realized one issue, I think dataloader in common lib should be used to define APIs and providing most common functions, but I realized actually you are also put actual dataloader there, https://github.com/intel/e2eAIOK/blob/main/e2eAIOK/common/trainer/data_builder.py#L19, https://github.com/intel/e2eAIOK/blob/e8dcbf633d7b4b1952d08ffc03425fdf898aaedc/e2eAIOK/common/trainer/data/nlp_build_datasets.py
> > > I would like to confirm that adding cifar10, SQuAD and other dataset is a common work or can we put https://github.com/intel/e2eAIOK/blob/main/e2eAIOK/common/trainer/data_builder.py#L19-L47 to a seperate file and leaving the most basic function here?
> > 
> > 
> > Thanks for your suggestions. I will refactor this code.
> 
> You can refer to the code on Model Adapter. We only keep the most common operations(get dataset and dataloader) in common file: https://github.com/intel-innersource/frameworks.bigdata.AIDK/blob/transfer_learning/AIDK/TransferLearningKit/src/dataset/__init__.py For each dataset, we will write a individual loader for it, such as: https://github.com/intel-innersource/frameworks.bigdata.AIDK/blob/transfer_learning/AIDK/TransferLearningKit/src/dataset/cifar100.py

Good suggestions. I will refer to it for the following refining.

**Comment by tianyil1** [comment]
Refactored the BERT trainer. Please help review this PR. @xuechendi

**Review by xuechendi — APPROVED** [review]
LGTM

**Comment by xuechendi** [comment]
@tianyil1 , PR looks good to me, if there is no further update, I'll merge it

**Comment by tianyil1** [comment]
> @tianyil1 , PR looks good to me, if there is no further update, I'll merge it

Yes, no further update in this PR. @xuechendi

**Pull request merged**
