### PR TITLE
[v1.0] Refine CNN EA process, align with ZenNAS EA

### PR DESCRIPTION
**Pull request by zigzagcai**
1. Make DE-NAS CNN EA algorithm and parameter aligned with ZenNAS EA algorithm and parameter

### CODE REVIEW

**Comment by zigzagcai** [comment]
Completed

**Review by xuechendi — APPROVED** [review]
LGTM, since the change is small, we can skip CI/CD

**Comment by xuechendi** [comment]
@zigzagcai , I reviewed this PR, looks good to me, since the change is small, if you would like to, we can skip CI/CD and merge it. Otherwise, please submit a new commit to trigger CI/CD

**Comment by zigzagcai** [comment]
Completed refine, CNN EA aligned with ZenNAS EA

**Pull request merged**
