### PR TITLE
[v1.1][ISSUE-228] colab notebook demos for DE-NAS CNN

### PR DESCRIPTION
**Pull request by Peach-He**
### What changes were proposed in this pull request?

provide pip install notebook demo for DE-NAS CNN

### Why are the changes needed?

support run colab notebook or non-docker env

### How was this patch tested?

CI/CD covered test

### CODE REVIEW

**Comment by Peach-He** [comment]
@Jian-Zhang refined DE-NAS CNN notebook

**Comment by xuechendi** [comment]
@Peach-He , I saw no data prepare?

**Comment by Peach-He** [comment]
> @Peach-He , I saw no data prepare?

Training data is downloaded automatically by torchvision datasets API, so we don't need to prepare dataset manually.

**Comment by tianyil1** [comment]
@Peach-He I saw some CNN-related content in the [cv demo](https://github.com/intel/e2eAIOK/blob/main/demo/denas/computer_vision/DENAS_COMPUTER_VISION_DEMO.ipynb) and suggested you can add it to this demo. And I will clear the content in that demo for ViT only.

**Review by xuechendi — APPROVED** [review]
LGTM

**Pull request merged**
