### PR TITLE
[v0.3 Demo] Demo for DE-NAS Summary/CV/NLP/ASR

### PR DESCRIPTION
**Pull request by zigzagcai**
DE-NAS Demo Completed.
Including:
1. [DE-NAS Summary](http://sr602:8888/notebooks/demo/denas/DENAS_SUMMARY.ipynb), Edit by Zheng
2. [DE-NAS CV](http://sr602:8888/notebooks/demo/denas/computer_vision/DENAS_COMPUTER_VISION_DEMO.ipynb), Edit by Bin
3. [DE-NAS NLP](http://sr602:8888/notebooks/demo/denas/bert/DENAS_BERT_DEMO.ipynb), Edit By Tianyi
4. [DE-NAS ASR](http://sr602:8888/notebooks/demo/denas/asr/DENAS_ASR_DEMO.ipynb), Edit by Tao

### CODE REVIEW

**Comment by zigzagcai** [comment]
Completed.

**Comment by xuechendi** [comment]
Thanks! Let's start demo review and refine this week

**Comment by xuechendi** [comment]
@Jian-Zhang , @zhouyu5, @XinyaoWa , @xuechendi please take a look at http://sr602:8888/tree/demo/denas, and leave your review comments here by Wed

**Comment by xuechendi** [comment]
Chendi's comments:
* summary page -> 
    1. would be better to add a link to invidividual page
* CV page ->
    1. Add DeNas search space intro
    2. Add performance Overview bullet
* Bert Page ->
    1. the Graph is all blue, can we tune the color?
* ASR page ->
    1. Looks good to me

**Comment by zigzagcai** [comment]
summary page ->
would be better to add a link to invidividual page
-------------------------------------------------------------------------------
Link for individual demo pages already exists at the bottom of summary demo page:
image

**Comment by zhouyu5** [comment]
In order to avoid repetition, I mainly add the unmentioned parts：
- summary page
    - In the subsection "Hardware-Aware Unified Search Framework", it look not clear where it is related with hardware.
    - It would be more clear if you could add a table, demostrating the searched model in CV,NLP,ASR domain and their performance.
    - It would be better if you could add a short introduction of the train-free score and their reference.
    
- CV page, Bert Page, ASR page
    - Missing an inference part.
    - It would be better to introduce the tasks and datasets.
    - It would be better if you could add a comparion with stock model on their params, FLOPS, throughput and etc. (ResNet/ViT for CV, BERT for NLP, RNNT for ASR).
    - It would be better to add a serarched model architecture, I recommend to use `hiddenlayer` package, it can export model to pdf.
      ```python
      import hiddenlayer as hl
      g = hl.build_graph(network, dummy_input, transforms=None)
      g.save(join(self.output_folder, "network_architecture.pdf"))
      del g
      ```
- CV page
    - It might be more clear to introduce the CNN based and ViT based model separately instead of a combined introduction

**Comment by zigzagcai** [comment]
Completed refine and ready for merge.

**Comment by zigzagcai** [comment]
> summary page
> 
> * In the subsection "Hardware-Aware Unified Search Framework", it look not clear where it is related with hardware.
> * It would be more clear if you could add a table, demostrating the searched model in CV,NLP,ASR domain and their performance.
> * It would be better if you could add a short introduction of the train-free score and their reference.

- Hardware-Aware mainly related with the coarsed-grained `budget latency` and fine-grained `latency score`. Since it is a demo page and won't touch too much details, users who are intetrested can read DE-NAS blog for future reference.
- Same with above, it is a demo page and won't touch too much details about train-free score, users who are interested can read DE-NAS blog for future reference.
- Performance Table will be added when the DE-NAS PDT approved performance is ready.

**Comment by zigzagcai** [comment]
> @zigzagcai Please remove the unused pictures.

Got it. I have removed unused pictures.

**Review by Jian-Zhang — COMMENTED** [review]
LGTM.

**Pull request merged**
