### PR TITLE
[v1.1][ISSUE-218] DLRM demo update with fixes on infer error

### PR DESCRIPTION
**Pull request by xuechendi**
### What changes were proposed in this pull request?
* update dlrm demo
* update SDA dlrm advisor with customize script path
* update dlrm patch to fix infer fail issue

### Why are the changes needed?
use unified workflow_prepare.sh

### How was this patch tested?
existing CI/CD
manual notebook run

### CODE REVIEW

**Comment by xuechendi** [comment]
image

image

**Comment by xuechendi** [comment]
@zigzagcai , I found USE_NUMPY=1 is not working on SR602 as well. I tested with my local env, and force to use NUMPY fix this issue.
image

image

**Comment by zigzagcai** [comment]
> 

I find in the latest test results, sr602 still has the previous error.

**Comment by xuechendi** [comment]
> > 
> 
> I find in the latest test results, sr602 still has the previous error.

yes, I found this is very strange, using pip install or conda install, all shows numpy already installed, but torch continually report numpy is not found, which cause this issue.

**Comment by zigzagcai** [comment]
> > > 
> > 
> > 
> > I find in the latest test results, sr602 still has the previous error.
> 
> yes, I found this is very strange, using pip install or conda install, all shows numpy already installed, but torch continually report numpy is not found, which cause this issue.

@xuechendi , I have fixed this error in https://github.com/intel/e2eAIOK/pull/273. The root cause is version conflict between numpy and torch1.5

**Pull request merged**
