### PR TITLE
[v1.2][ISSUE-356] Enable Deltatuner CI/CD

### PR DESCRIPTION
**Pull request by zhouyu5**

### CODE REVIEW

**Comment by xuechendi** [comment]
image

**Comment by xuechendi** [comment]
@zhouyu5 @tianyil1 @XinyaoWa , all UT are failed due to env setting

**Comment by zhouyu5** [comment]
> @zhouyu5 @tianyil1 @XinyaoWa , all UT are failed due to env setting

Got it. Let me have a check.

**Comment by zhouyu5** [comment]
> @zhouyu5 @tianyil1 @XinyaoWa , all UT are failed due to env setting

@xuechendi All test have been passed, please have a check. It is now ready to merge.

**Comment by tianyil1** [comment]
LGTM.

**Review by xuechendi — APPROVED** [review]
LGTM

**Pull request merged**
