### PR TITLE
[v1.2][ISSUE-306]Add language_identify_spark interface

### PR DESCRIPTION
**Pull request by haojinIntel**
### What changes were proposed in this pull request?

provide language identify spark interface version

### Why are the changes needed?

For EasyData request

### How was this patch tested?

UT

### CODE REVIEW

**Comment by haojinIntel** [comment]
retest this please

**Review by xuechendi — APPROVED** [review]
LGTM

**Comment by xuechendi** [comment]
@haojinIntel, I tried using colab, the PR looks good to me, But seems it kept failing on in-lab server behind proxy. Please check if the SSLerror failing is consistent or just happens today? If it happens consistently, we need to find a way to workaround

**Comment by haojinIntel** [comment]
@xuechendi Hi chendi, I've downloaded the model onto local machines. Now the UT test can work well.

**Pull request merged**
