### PR TITLE
[v1.1][ISSUE-222]Model Adapter Demos refinement

### PR DESCRIPTION
**Pull request by XinyaoWa**
- Remove built-in links in Readme
- Refine demos for Model Adapter: update content, add descriptions to each box

### CODE REVIEW

**Review by xuechendi — APPROVED** [review]
LGTM, if no further changes planned, I'll merge it

**Comment by xuechendi** [comment]
I am not sure about the menu: from my notes, it should looks like:
I know now you have only "Model Adaptor Finetuner Overview" under "Overview", but after performance approved, you'll have second bullet, so may be we should create sub-level title now?
image

**Comment by XinyaoWa** [comment]
> 

Have modified

**Review by xuechendi — APPROVED** [review]
LGTM

**Pull request merged**
