### PR TITLE
[v1.1][ISSUE-195]DE-NAS CV on ImageNet 1K dataset

### PR DESCRIPTION
**Pull request by csdingbin**
### What changes were proposed in this pull request?

Add the large dataset of ImageNet 1K for DE-NAS CV both search and trainer

### Why are the changes needed?

Support large dataset of ImageNet 1K  for DE-NAS CV

### How was this patch tested?

The test was added into the CI/CD Integration Test DeNas.

### CODE REVIEW

**Comment by xuechendi** [comment]
@csdingbin , please paste the CI/CD screen shot for this new search path here.

**Review by xuechendi — APPROVED** [review]
Codes looking good, pending for CI/CD coverage evidence.

**Comment by csdingbin** [comment]
> @csdingbin , please paste the CI/CD screen shot for this new search path here.

image

**Comment by xuechendi** [comment]
@csdingbin , I only saw the one for cifar10, can you point me the search for imagenet1k?
image

**Comment by csdingbin** [comment]
> @csdingbin , I only saw the one for cifar10, can you point me the search for imagenet1k? image

Imagenet1K is too large, it's not suitable to add this test to CI/CD, the trainer used is same with CIFAR10. And I had tested works well for my local tests. So I think It is suitable to use CIFAR10 test to cover this PR.

**Comment by xuechendi** [comment]
> > @csdingbin , I only saw the one for cifar10, can you point me the search for imagenet1k? image
> 
> Imagenet1K is too large, it's not suitable to add this test to CI/CD, the trainer used is same with CIFAR10. And I had tested works well for my local tests. So I think It is suitable to use CIFAR10 test to cover this PR.

@csdingbin , I think you said search for imagenet1K is very fast? If training is too slow, can we only train one iter? 
We are trying to make sure all new features will have CI/CD or UT coverage, so it won't go wrong in future.

**Comment by csdingbin** [comment]
@xuechendi  CI/CD tests for ImageNet added. And passed.
image

**Pull request merged**
