### PR TITLE
[v0.3] code refine, pass cicd

### PR DESCRIPTION
**Pull request by zigzagcai**
1. minor fix about cicd scripts, passed cicd for v0.1/v0.2 workloads and denas tests
2. refine Dockerfiles
3. refine docs

### CODE REVIEW

**Comment by zigzagcai** [comment]
@xuechendi Please help to review and merge this PR.
Mainly about minor fix about cicd scirpts

**Comment by zigzagcai** [comment]
Completed development and [passed CICD tests](https://github.com/intel-innersource/frameworks.bigdata.AIDK/pull/323)

**Comment by zigzagcai** [comment]
Can you help to review and merge this PR. This PR mainly about fix for Dockerfile and CICD files.
@xuechendi

**Comment by xuechendi** [comment]
> Can you help to review and merge this PR? This PR mainly about fix for Dockerfile and CICD files. @xuechendi

since we are now merge denas PR, will wait until other remaining two PR merged.

**Review by xuechendi — APPROVED** [review]
synced with @zigzagcai , LGTM

**Pull request merged**
