### PR TITLE
[v1.2][ISSUE-306] Support toxicity score

### PR DESCRIPTION
**Pull request by haojinIntel**
### What changes were proposed in this pull request?

Support to give the toxicity score for each doc.

### Why are the changes needed?

To filter more doc with toxicity content.

### CODE REVIEW

**Comment by xuechendi** [comment]
@haojinIntel , please install perspective in setup.py

**Comment by haojinIntel** [comment]
@xuechendi The toxicity scores of perspectiveAPI and detoxify lib:
image

**Comment by xuechendi** [comment]
provide detoxify source: https://github.com/unitaryai/detoxify

**Review by xuechendi — APPROVED** [review]
LGTM

**Comment by xuechendi** [comment]
@haojinIntel , codes looks good to me, for examples, can we test with c4? There will be more toxicity data in C4 so we can test on that.

**Pull request merged**
