### PR TITLE
[WIP][v1.1][ISSUE-209] update oneapi version

### PR DESCRIPTION
**Pull request by zhouyu5**
### What changes were proposed in this pull request?

Update the oneapi version.

### Why are the changes needed?

To support performance test.

### How was this patch tested?

Existing ci/cd workflow.

### CODE REVIEW

**Comment by zhouyu5** [comment]
@Peach-He please have a review.

**Review by XinyaoWa — APPROVED** [review]

**Comment by xuechendi** [comment]
@zhouyu5 and @XinyaoWa , Tao's request here is more focus on performance perspective, can you share data if performance will be different after change to 2023.0

**Comment by xuechendi** [comment]
and we can leverage CI/CD for functionality validation.

**Review by Peach-He — APPROVED** [review]

**Comment by Peach-He** [comment]
This PR is going to leverage CICD to build new docker image, and will be merged after performance evaluation.

**Comment by zhouyu5** [comment]
> @zhouyu5 and @XinyaoWa , Tao's request here is more focus on performance perspective, can you share data if performance will be different after change to 2023.0

After change oneapi to 2023.0, per epoch time show only slightly change (3245s vs 3218s), we can conclude that we can safely upgrade the oneapi version.

**Comment by XinyaoWa** [comment]
> @zhouyu5 and @XinyaoWa , Tao's request here is more focus on performance perspective, can you share data if performance will be different after change to 2023.0

I have tested on Fine-tuner and Distiller in new env, all only bring small change. 
image

**Comment by XinyaoWa** [comment]
> > @zhouyu5 and @XinyaoWa , Tao's request here is more focus on performance perspective, can you share data if performance will be different after change to 2023.0
> 
> After change oneapi to 2023.0, per epoch time show only slightly change (3245s vs 3218s), we can conclude that we can safely upgrade the oneapi version.

I tested Finetuner and Distiller in new env, both only bring small changes: finetuner 460s vs. 431s, Distiller 123s vs.114s. I think it's safe to update the docker.

**Comment by xuechendi** [comment]
@zhouyu5 @XinyaoWa , thanks for updating the performance.
According to CI/CD, seems upgrading to 2023.0 will cause some library incompatible for any workloads used IPEX. I suggested you two only update performance PDT slides based on 2023.0 and leave this PR pending until we fix IPEX issue

**Comment by xuechendi** [comment]
> @zhouyu5 @XinyaoWa , thanks for updating the performance. According to CI/CD, seems upgrading to 2023.0 will cause some library incompatible for any workloads used IPEX. I suggested you two only update performance PDT slides based on 2023.0 and leave this PR pending until we fix IPEX issue

After syncing with @zhouyu5 , seems upgrade pytorch to 1.12.1 will fix this issue, @zhouyu5 will follow on this.

**Comment by xuechendi** [comment]
@Peach-He , after @zhouyu5 upgrade oneapi to 2023.0 with replace ipex and torch with 1.12.100, there is a segment fault error when running ASR training. I'll set up a meeting to discuss this issue.

**Comment by zhouyu5** [comment]
Network issue, will reopen PR for restart CI/CD.

**Review by xuechendi — APPROVED** [review]
approved

**Pull request merged**
