### PR TITLE
[v1.1] [ISSUE-211] combine torch110 and torch112 docker file

### PR DESCRIPTION
**Pull request by Peach-He**
### What changes were proposed in this pull request?

combine dockerfile of pytorch 1.10 and pytorch 1.12, only maintain pytorch 1.12 dockerfile

### Why are the changes needed?

pytorch 1.10 dockerfile is just for RNN-T and RNN-T is runnable with pytorch 1.12, so that we can maintain just one pytorch docker.

### How was this patch tested?

Existing ci/cd workflow covered test.

### CODE REVIEW

**Comment by xuechendi** [comment]
@Peach-He , I merged Yu's PR, please update

**Comment by Peach-He** [comment]
> @Peach-He , I merged Yu's PR, please update

rebased main code, please have a review. The failed UT can be safely ignored since it ran successfully before, some test may failed due to network issue.

**Comment by Peach-He** [comment]
@xuechendi this PR is ready to merge

**Review by xuechendi — APPROVED** [review]
passed CI/CD, looks good

**Pull request merged**
