### PR TITLE
[v1.1][ISSUE-183] Combine DE-NAS Configuration Settings

### PR DESCRIPTION
**Pull request by tianyil1**
### What changes were proposed in this pull request?

1. Combined the DE-NAS configuration files of search settings and supernet/search_space settings used in each domain.
2. Accordingly changed the usage of the search trigger file.

### Why are the changes needed?

Refined the DE-NAS configuration settings, and combined settings into one file for simplifying the user configuration.

### How was this patch tested?

Existing DE-NAS unittest covers the changes in this PR.

### CODE REVIEW

**Comment by tianyil1** [comment]
Please help review this PR. Thx. @xuechendi

**Review by xuechendi — APPROVED** [review]
Looks perfect

**Comment by xuechendi** [comment]
@tianyil1 , I just checked the PR, it looks perfect to me, if there is no follow ups, I'll go merging it. Thanks

**Comment by tianyil1** [comment]
> @tianyil1 , I just checked the PR, it looks perfect to me, if there is no follow ups, I'll go merging it. Thanks

There is no further update in this PR. Thx.

**Pull request merged**
