### PR TITLE
[v1.2][ISSUE-351]remove resnet18 downloading for ma unit test

### PR DESCRIPTION
**Pull request by XinyaoWa**
remove resnet18 downloading for ma unit test to avoid network issue

### CODE REVIEW

**Comment by XinyaoWa** [comment]
> @XinyaoWa , what is the background for this PR?

Before in UT, we need to download resnet18, but always fail due to network issue. Now I put the downloaded weights on the testing server to avoid this issue.

**Comment by xuechendi** [comment]
> > @XinyaoWa , what is the background for this PR?
> 
> Before in UT, we need to download resnet18, but always fail due to network issue. Now I put the downloaded weights on the testing server to avoid this issue.

Thanks for clarification, I merge UT pr firstly, which leads to a conflict here. Please help to fix it, I'll merge this PR later.

**Comment by XinyaoWa** [comment]
> > > @XinyaoWa , what is the background for this PR?
> > 
> > 
> > Before in UT, we need to download resnet18, but always fail due to network issue. Now I put the downloaded weights on the testing server to avoid this issue.
> 
> Thanks for clarification, I merge UT pr firstly, which leads to a conflict here. Please help to fix it, I'll merge this PR later.

fixed, please have a check.

**Review by xuechendi — APPROVED** [review]
LGTM

**Pull request merged**
